"""SOTA Python Sandbox Executor for Tool Calling.

Ensures that code generated by the agent is executed in an isolated 
subprocess, capturing stdout and stderr. This grounds the LLM's reasoning
in physical execution reality rather than hallucinated correctness.
"""
import subprocess
import tempfile
import os
import ast
from loguru import logger
from typing import Dict, Any

class CodeSandbox:
    @staticmethod
    def _is_safe_code(code: str) -> bool:
        """Basic static analysis to prevent obvious malicious OS calls in the sandbox."""
        try:
            tree = ast.parse(code)
            for node in ast.walk(tree):
                if isinstance(node, ast.Import) or isinstance(node, ast.ImportFrom):
                    for alias in node.names:
                        if alias.name in ['os', 'subprocess', 'sys', 'shutil']:
                            logger.warning(f"Sandbox rejected import of unsafe module: {alias.name}")
                            return False
            return True
        except SyntaxError:
            return False # Let python catch it on execution

    @staticmethod
    def execute(code: str, timeout: int = 5) -> Dict[str, Any]:
        """Executes Python code and returns output, errors, and success flag."""
        logger.info("🛠️ [Sandbox] Spawning isolated subprocess to execute Agent's code...")
        
        if not CodeSandbox._is_safe_code(code):
            return {"success": False, "output": "", "error": "Execution denied: Unsafe imports detected (os, sys, subprocess)."}
            
        with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as f:
            f.write(code)
            temp_path = f.name
            
        try:
            result = subprocess.run(
                ["python3", temp_path], 
                capture_output=True, 
                text=True, 
                timeout=timeout
            )
            success = result.returncode == 0
            return {
                "success": success,
                "output": result.stdout[:2000],  # Cap to prevent context bloat
                "error": result.stderr[:2000] if not success else ""
            }
        except subprocess.TimeoutExpired:
            return {"success": False, "output": "", "error": f"Execution Timed Out ({timeout}s). Infinite loop detected."}
        except Exception as e:
            return {"success": False, "output": "", "error": f"System execution fault: {e}"}
        finally:
            if os.path.exists(temp_path):
                os.remove(temp_path)
