"""L2: Meta-Prompting Conductor (Dynamic Agent Dispatcher).

Unlike static pipelines, this Conductor acts as a dynamic router.
It uses an LLM to analyze the problem, determine exactly which 'Expert Personas' 
are needed (e.g., Python Expert, Math Expert), and invokes them asynchronously.
"""
import asyncio
from typing import Dict, Any, List
from pydantic import BaseModel, Field
from loguru import logger
from arsenal_ai.engine.llm import agenerate_structured
from arsenal_ai.core.models import ArsenalConfig, TaskSpec

class ExpertCall(BaseModel):
    """Schema representing a sub-task dispatched to an expert."""
    expert_name: str = Field(description="Name of the persona, e.g., 'Python_Architect' or 'Math_Logician'")
    instruction: str = Field(description="Highly specific instructions for this expert.")

class ConductorPlan(BaseModel):
    """The master plan generated by the Conductor."""
    experts_required: List[ExpertCall] = Field(description="List of experts to spin up concurrently.")
    synthesis_strategy: str = Field(description="How to merge their outputs once they return.")

class GenericExpertOutput(BaseModel):
    """Schema for the output generated by an invoked expert."""
    analysis: str = Field(description="The expert's deep reasoning and findings.")
    code_or_data: Optional[str] = Field(default=None, description="Any artifacts produced.")

class MetaConductor:
    def __init__(self, config: ArsenalConfig):
        self.config = config

    async def _invoke_expert(self, call: ExpertCall, context: str) -> Dict[str, Any]:
        """Spins up an LLM with the specified persona to solve the sub-task."""
        logger.debug(f"🤖 [L2 Conductor] Booting Expert: {call.expert_name}")
        messages = [
            {"role": "system", "content": f"You are a specialized expert: {call.expert_name}. Obey the conductor's instructions rigorously."},
            {"role": "user", "content": f"Context: {context}\n\nTask: {call.instruction}"}
        ]
        
        try:
            result: GenericExpertOutput = await agenerate_structured(
                messages=messages,
                response_model=GenericExpertOutput,
                model=self.config.target_model,
                api_base=self.config.api_base,
                api_key=self.config.api_key
            )
            return {"expert": call.expert_name, "output": result.model_dump()}
        except Exception as e:
            logger.warning(f"Expert {call.expert_name} failed: {e}")
            return {"expert": call.expert_name, "error": str(e)}

    async def conduct(self, task: TaskSpec) -> Dict[str, Any]:
        """The main Meta-Prompting entry point."""
        logger.info(f"🎼 [L2 Conductor] Analyzing task to draft Meta-Prompting plan...")
        
        # 1. Draft the Plan
        plan_msgs = [
            {"role": "system", "content": "You are the Meta-Prompting Conductor. Break down the user's task into specialized sub-tasks and assign them to imaginary experts."},
            {"role": "user", "content": f"Task: {task.description}"}
        ]
        plan: ConductorPlan = await agenerate_structured(
            messages=plan_msgs,
            response_model=ConductorPlan,
            model=self.config.target_model,
            api_base=self.config.api_base,
            api_key=self.config.api_key
        )
        
        logger.info(f"🎼 [L2 Conductor] Plan finalized. Dispatching {len(plan.experts_required)} experts concurrently...")
        
        # 2. Execute Experts Concurrently (SOTA Asynchronous Dispatch)
        tasks = [self._invoke_expert(expert, task.description) for expert in plan.experts_required]
        results = await asyncio.gather(*tasks)
        
        # 3. Aggregate Results
        final_bundle = {res["expert"]: res for res in results}
        logger.success("🎼 [L2 Conductor] All experts have reported back.")
        return final_bundle
