"""L2: Meta-Prompting Conductor (Dynamic Agent Dispatcher).

Unlike static pipelines, this Conductor acts as a dynamic router.
It uses an LLM to analyze the problem, determine exactly which 'Expert Personas' 
are needed (e.g., Python Expert, Math Expert), and invokes them asynchronously.
"""
import asyncio
from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field
from loguru import logger
from arsenal_ai.engine.llm import agenerate_structured
from arsenal_ai.core.models import ArsenalConfig, TaskSpec
from arsenal_ai.tools.executor import CodeSandbox

class ExpertCall(BaseModel):
    """Schema representing a sub-task dispatched to an expert."""
    expert_name: str = Field(description="Name of the persona, e.g., 'Python_Architect' or 'Math_Logician'")
    instruction: str = Field(description="Highly specific instructions for this expert.")

class ConductorPlan(BaseModel):
    """The master plan generated by the Conductor."""
    experts_required: List[ExpertCall] = Field(description="List of experts to spin up concurrently.")
    synthesis_strategy: str = Field(description="How to merge their outputs once they return.")

class ExecutableAction(BaseModel):
    reasoning: str = Field(description="Step-by-step logic.")
    python_code_to_execute: Optional[str] = Field(default=None, description="Valid Python code to run in the Sandbox to verify the theory. Do NOT use OS/Sys imports.")

class GenericExpertOutput(BaseModel):
    """Schema for the final output generated by an invoked expert after testing."""
    analysis: str = Field(description="The expert's deep reasoning and findings.")
    verified_code: Optional[str] = Field(default=None, description="Code that has been executed and confirmed to work.")
    execution_logs: Optional[str] = Field(default=None, description="Stdout or Stderr from the Sandbox.")


class MetaConductor:
    def __init__(self, config: ArsenalConfig):
        self.config = config

    async def _invoke_expert(self, call: ExpertCall, context: str) -> Dict[str, Any]:
        """Spins up an LLM with Sandbox access to execute and verify its work (ReAct style)."""
        logger.debug(f"🤖 [L2 Conductor] Booting Expert: {call.expert_name}")
        
        messages = [
            {"role": "system", "content": f"You are a specialized expert: {call.expert_name}. Obey the conductor's instructions. If the task involves code or math, you MUST write python_code_to_execute. The system will run it and give you the output."},
            {"role": "user", "content": f"Context: {context}

Task: {call.instruction}"}
        ]
        
        try:
            # Step 1: Generate proposed action
            action: ExecutableAction = await agenerate_structured(
                messages=messages,
                response_model=ExecutableAction,
                model=self.config.target_model,
                api_base=self.config.api_base,
                api_key=self.config.api_key
            )
            
            verified_code = None
            execution_logs = "No execution required."
            
            # Step 2: Tool Execution (Environment Feedback)
            if action.python_code_to_execute:
                sandbox_result = CodeSandbox.execute(action.python_code_to_execute)
                if sandbox_result["success"]:
                    logger.success(f"🤖 [{call.expert_name}] Sandbox Execution Succeeded!")
                    verified_code = action.python_code_to_execute
                    execution_logs = sandbox_result["output"]
                else:
                    logger.warning(f"🤖 [{call.expert_name}] Sandbox Execution Failed. Feeding error back to expert...")
                    execution_logs = sandbox_result["error"]
                    # Step 3: Self-Correction Loop (One attempt to fix based on traceback)
                    correction_messages = messages + [
                        {"role": "assistant", "content": f"I tried running this code:
{action.python_code_to_execute}"},
                        {"role": "user", "content": f"The execution FAILED with this traceback:
{execution_logs}
Fix the code and output the corrected version."}
                    ]
                    correction_action: ExecutableAction = await agenerate_structured(
                        messages=correction_messages, response_model=ExecutableAction,
                        model=self.config.target_model, api_base=self.config.api_base, api_key=self.config.api_key
                    )
                    
                    if correction_action.python_code_to_execute:
                        retry_result = CodeSandbox.execute(correction_action.python_code_to_execute)
                        if retry_result["success"]:
                            logger.success(f"🤖 [{call.expert_name}] Self-Correction Succeeded!")
                            verified_code = correction_action.python_code_to_execute
                            execution_logs = retry_result["output"]
                        else:
                            logger.error(f"🤖 [{call.expert_name}] Self-Correction Failed. Outputting broken code.")
                            verified_code = correction_action.python_code_to_execute
                            execution_logs = retry_result["error"]

            final_output = GenericExpertOutput(
                analysis=action.reasoning,
                verified_code=verified_code,
                execution_logs=execution_logs
            )
            return {"expert": call.expert_name, "output": final_output.model_dump()}
            
        except Exception as e:
            logger.warning(f"Expert {call.expert_name} crashed: {e}")
            return {"expert": call.expert_name, "error": str(e)}    async def conduct(self, task: TaskSpec) -> Dict[str, Any]:
        """The main Meta-Prompting entry point."""
        logger.info(f"🎼 [L2 Conductor] Analyzing task to draft Meta-Prompting plan...")
        
        # 1. Draft the Plan
        plan_msgs = [
            {"role": "system", "content": "You are the Meta-Prompting Conductor. Break down the user's task into specialized sub-tasks and assign them to imaginary experts."},
            {"role": "user", "content": f"Task: {task.description}"}
        ]
        plan: ConductorPlan = await agenerate_structured(
            messages=plan_msgs,
            response_model=ConductorPlan,
            model=self.config.target_model,
            api_base=self.config.api_base,
            api_key=self.config.api_key
        )
        
        logger.info(f"🎼 [L2 Conductor] Plan finalized. Dispatching {len(plan.experts_required)} experts concurrently...")
        
        # 2. Execute Experts Concurrently (SOTA Asynchronous Dispatch)
        tasks = [self._invoke_expert(expert, task.description) for expert in plan.experts_required]
        results = await asyncio.gather(*tasks)
        
        # 3. Aggregate Results
        final_bundle = {res["expert"]: res for res in results}
        logger.success("🎼 [L2 Conductor] All experts have reported back.")
        return final_bundle
